---
- name: apt install
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: latest
    update_cache: yes

- name: Add key
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    apt-key fingerprint 0EBFCD88
    add-apt-repository    "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  args:
    warn: no

- name: install docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io



#- name: start service apache2 and enable it.
#  service:
#    name: apache2
#    state: started
#    enabled: True
